//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIPS.ControlMenor.PanelControl {
    
    
    public partial class Default {
        
        /// <summary>
        /// ddlEfector control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlEfector;
        
        /// <summary>
        /// txtFInicio control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtFInicio;
        
        /// <summary>
        /// txtFFin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.TextBox txtFFin;
        
        /// <summary>
        /// btnFiltrar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnFiltrar;
        
        /// <summary>
        /// tabs control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl tabs;
        
        /// <summary>
        /// InformacionPorEdad6meses control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIPS.ControlMenor.PanelControl.InformacionPorEdad InformacionPorEdad6meses;
        
        /// <summary>
        /// InformacionPorEdad12meses control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIPS.ControlMenor.PanelControl.InformacionPorEdad InformacionPorEdad12meses;
        
        /// <summary>
        /// InformacionPorEdad2anios control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIPS.ControlMenor.PanelControl.InformacionPorEdad InformacionPorEdad2anios;
        
        /// <summary>
        /// InformacionPorEdad3anios control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIPS.ControlMenor.PanelControl.InformacionPorEdad InformacionPorEdad3anios;
        
        /// <summary>
        /// InformacionPorEdad4anios control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIPS.ControlMenor.PanelControl.InformacionPorEdad InformacionPorEdad4anios;
        
        /// <summary>
        /// InformacionPorEdad5anios control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIPS.ControlMenor.PanelControl.InformacionPorEdad InformacionPorEdad5anios;
        
        /// <summary>
        /// InformacionPorEdad6anios control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SIPS.ControlMenor.PanelControl.InformacionPorEdad InformacionPorEdad6anios;
    }
}
